CREATE TABLE llx_dolistoreextract_order (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	dolistore_order_ref varchar(128) DEFAULT NULL,
	dolistore_order_date date DEFAULT NULL,
	release_date date DEFAULT NULL,
	currency_code varchar(3) DEFAULT 'EUR',
	total_ht double(24,8) DEFAULT 0,
	total_tva double(24,8) DEFAULT 0,
	total_ttc double(24,8) DEFAULT 0,
	commission_percent double(10,4) DEFAULT 0,
	billable_total_ht double(24,8) DEFAULT 0,
	customer_name varchar(255) DEFAULT NULL,
	customer_email varchar(255) DEFAULT NULL,
	customer_country varchar(255) DEFAULT NULL,
	customer_country_code varchar(8) DEFAULT NULL,
	fk_soc_customer integer DEFAULT NULL,
	fk_contact_customer integer DEFAULT NULL,
	fk_soc_dolistore integer DEFAULT NULL,
	fk_facture integer DEFAULT NULL,
	invoice_date date DEFAULT NULL,
	email_message_id varchar(255) DEFAULT NULL,
	email_subject varchar(255) DEFAULT NULL,
	email_date datetime DEFAULT NULL,
	email_uid integer DEFAULT NULL,
	email_folder varchar(255) DEFAULT NULL,
	raw_hash varchar(128) DEFAULT NULL,
	status smallint DEFAULT 0 NOT NULL,
	note_public text,
	note_private text,
	model_pdf varchar(255) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	datec datetime DEFAULT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer DEFAULT NULL,
	fk_user_modif integer DEFAULT NULL
) ENGINE=innodb;
