CREATE TABLE llx_dolistoreextract_order_line (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_order integer NOT NULL,
	product_dolistore_ref varchar(128) DEFAULT NULL,
	product_label varchar(255) DEFAULT NULL,
	fk_product integer DEFAULT NULL,
	qty double(24,8) DEFAULT 0,
	unit_price_ht double(24,8) DEFAULT 0,
	total_ht double(24,8) DEFAULT 0,
	total_tva double(24,8) DEFAULT 0,
	total_ttc double(24,8) DEFAULT 0,
	billable_unit_price_ht double(24,8) DEFAULT 0,
	billable_total_ht double(24,8) DEFAULT 0,
	tax_rate double(10,4) DEFAULT 0,
	description text,
	raw_hash varchar(128) DEFAULT NULL,
	status smallint DEFAULT 1 NOT NULL,
	import_key varchar(14) DEFAULT NULL,
	datec datetime DEFAULT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer DEFAULT NULL,
	fk_user_modif integer DEFAULT NULL
) ENGINE=innodb;
